stages:
  make_dataset:
    cmd: python ./src/data/make_dataset.py ./data/raw/Nyc_taxi_fare.csv
    deps:
    - ./src/data/make_dataset.py
    - ./data/raw/Nyc_taxi_fare.csv
    outs:
    - ./data/processed
    

  build_features:
    cmd: python ./src/features/build_features.py ./data/raw/Nyc_taxi_fare.csv
    deps:
    - ./src/features/build_features.py
    - ./data/raw/Nyc_taxi_fare.csv

    outs:
    - ./data/external