name: NYC Taxi Full CI/CD Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main


jobs:

  intergation:

    runs-on: ubuntu-latest


    steps:

    # ==========================================
    # CHECKOUT CODE
    # ==========================================
    - name: Checkout Repository
      uses: actions/checkout@v4


    # ==========================================
    # SETUP PYTHON
    # ==========================================
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"


    # ==========================================
    # INSTALL DEPENDENCIES
    # ==========================================
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-api.txt


    # ==========================================
    # INSTALL DVC + S3 SUPPORT
    # ==========================================
    - name: Install DVC
      run: |
        pip install "dvc[s3]"


    # ==========================================
    # CONFIGURE AWS CREDENTIALS
    # ==========================================
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.REGION }}


    # ==========================================
    # PULL DATA FROM DVC REMOTE
    # ==========================================
    - name: Pull Data From DVC Remote
      run: |
        dvc pull


    # ==========================================
    # RUN DVC PIPELINE
    # ==========================================
    - name: Run DVC Pipeline
      run: |
        dvc repro


    # ==========================================
    # PUSH UPDATED ARTIFACTS
    # ==========================================
    - name: Push Updated Artifacts
      run: |
        dvc push


    # ==========================================
    # LOGIN TO AMAZON ECR
    # ==========================================
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2


    # ==========================================
    # BUILD DOCKER IMAGE
    # ==========================================
    - name: Build Docker Image
      run: |
        docker build -t nyc-taxi-fare .


    # ==========================================
    # TAG DOCKER IMAGE
    # ==========================================
    - name: Tag Docker Image
      run: |
        docker tag nyc-taxi-fare:latest \
        ${{ secrets.ECR_URI }}/${{secrets.ECR_REPOSITRY}}:latest


    # ==========================================
    # PUSH IMAGE TO ECR
    # ==========================================
    - name: Push Docker Image To ECR
      run: |
        docker push \
        ${{ secrets.ECR_URI }}/${{secrets.ECR_REPOSITRY}}:latest


    # ==========================================
    # SUCCESS MESSAGE
    # ==========================================
    - name: Pipeline Success
      run: echo "CI/CD Pipeline Completed Successfully"


  # ==========================================
  # DEPLOY TO EC2
  # ==========================================
  Deployment:
    runs-on: self-hosted
    needs: intergation
    steps:
    - name: Deploy To EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}

        script: |

          # LOGIN TO ECR
          aws ecr get-login-password --region ${{ secrets.REGION }} | \
          docker login --username AWS --password-stdin ${{ secrets.ECR_URI }}

          # STOP OLD CONTAINER
          docker stop nyc-container || true

          # REMOVE OLD CONTAINER
          docker rm nyc-container || true

          # PULL LATEST IMAGE
          docker pull ${{ secrets.ECR_URI }}/nyc-taxi-fare:latest

          # RUN NEW CONTAINER
          docker run -d \
          --name nyc-container \
          -p 8000:8000 \
          ${{ secrets.ECR_URI }}/nyc-taxi-fare:latest

          